version: '3.2'
services:
  base: &base
    build:
      context: .
    volumes:
      - ./config:/config
      - ./output:/output
      - ./functions:/scripts/functions
    command: ["noop"]
  "dome-java": 
    <<: *base
    command: ["dome", "/config/java.yaml", "/config/dome.yaml", "/config/dome.java.yaml"]
  "dome-bedrock": 
    <<: *base
    command: ["dome", "/config/bedrock.yaml", "/config/dome.yaml", "/config/dome.bedrock.yaml"]
  "ring-java": 
    <<: *base
    command: ["ring", "/config/java.yaml", "/config/ring.yaml", "/config/ring.java.yaml"]
  "ring-bedrock": 
    <<: *base
    command: ["ring", "/config/bedrock.yaml", "/config/ring.yaml", "/config/ring.bedrock.yaml"]
  "cloudtree-java": 
    <<: *base
    command: ["cloudtree", "/config/java.yaml", "/config/cloudtree.yaml", "/config/cloudtree.java.yaml"]
  "cloudtree-bedrock": 
    <<: *base
    command: ["cloudtree", "/config/bedrock.yaml", "/config/cloudtree.yaml", "/config/cloudtree.bedrock.yaml"]
  "maze-java": 
    <<: *base
    command: ["maze", "/config/java.yaml", "/config/maze.yaml"]
