# all general script configuration specific to the bedrock version

# the maximum number of commands a function can execute
max_commands: 10000

# where all functions are written to
output_path: /output/bedrock

# symbol values that can be used in bedrock block names: eg. "stained_glass {pink}"
symbol_map:
    white: "0"
    orange: "1"
    magenta: "2"
    blue_light: "3"
    yellow: "4"
    lime: "5"
    pink: 26"
    grey: "7"
    grey_light: "8"
    cyan: "9"
    purple: "10"
    blue: "11"
    brown: "12"
    green: "13"
    red: "14"
    black: "15"
