# all general script configuration specific to the bedrock version

# the maximum number of commands a function can execute
max_commands: 10000

# where all functions are written to
output_path: /output/bedrock

# symbol values that can be used in bedrock block names: eg. "stained_glass {pink}"
symbol_map:
    white: "0"
    orange: "1"
    magenta: "2"
    blue_light: "3"
    yellow: "4"
    lime: "5"
    pink: "6"
    grey: "7"
    grey_light: "8"
    cyan: "9"
    purple: "10"
    blue: "11"
    brown: "12"
    green: "13"
    red: "14"
    black: "15"
    # `leaves` data values defining leaf type
    # (https://minecraft.gamepedia.com/Bedrock_Edition_data_values)
    oak_leaves: "0"
    spruce_leaves: "1"
    birch_leaves: "2"
    jungle_leaves: "3"
    x_4: "4"
    x_5: "5"
    x_6: "6"
    x_7: "7"
    oak_leaves_2: "8"
    spruce_leaves_2: "9"
    birch_leaves_2: "10"
    jungle_leaves_2: "11"
    # `log` data values defining wood type and direction
    # (https://minecraft.gamepedia.com/Bedrock_Edition_data_values)
    oak_ud: "0"
    spruce_ud: "1"
    birch_ud: "2"
    jungle_ud: "3"
    oak_ew: "4"
    spruce_ew: "5"
    birch_ew: "6"
    jungle_ew: "7"
    oak_ns: "8"
    spruce_ns: "9"
    birch_ns: "10"
    jungle_ns: "11"
