# types of leaves randomly selected
leaves_sample:
    - "leaves {oak_leaves}"
    - "leaves {birch_leaves}"
    
# The log blocks used (ordered to match DIRECTIONS)
log_blocks:
    - "log {oak_ud}"
    - "log {oak_ns}"
    - "log {oak_ns}"
    - "log {oak_ew}"
    - "log {oak_ew}"
    - "log {oak_ud}"
