# the namespace of the functions
namespace: 'cloudtree'

# These are constants controlling aspects the branch's length:
# No branch is less that this
branch_min_length: 8

# Multiplies cross section index then added to length
branch_length_factor: 0.4

# Controls size of a random constant added to length
branch_variation_factor: 4

# A branch cannot extend down passed this z value (relative to actor)
lowest_branch_end: 10

# Where the trunk is placed relative to actor (the 1 is for the affine tranforms)
start_position: [0, 0, -2, 1]

# This overrides `branch_min_length` for the trunk
trunk_min_length: 30
