# all general script configuration specific to the java version

# the maximum number of commands a function can execute
max_commands: 65536

# where all functions are written to
output_path: /output/java
