# all configuration specific to generating a maze

name: 'small'

# symbol values that can be used in the `corners` and `edges` commands
symbol_map:
    wall_block: 'minecraft:blue_ice'

# render commands for the tile corners
corners:
    - 'setblock ~1 ~ ~1 {wall_block}'
    - 'setblock ~-1 ~ ~-1 {wall_block}'
    - 'setblock ~1 ~ ~-1 {wall_block}'
    - 'setblock ~-1 ~ ~1 {wall_block}'

# render commands for the tile edges
edges:
    - 'setblock ~-1 ~ ~0 {wall_block}'
    - 'setblock ~0 ~ ~1 {wall_block}'
    - 'setblock ~1 ~ ~0 {wall_block}'
    - 'setblock ~0 ~ ~-1 {wall_block}'

# defines the name of each tile and what edges they have
tiles:
    - ['0', [0]]
    - ['1', [1]]
    - ['2', [2]]
    - ['3', [3]]
    - ['4', [0, 3]]
    - ['5', [0, 1]]
    - ['6', [1, 2]]
    - ['7', [2, 3]]
    - ['8', [1, 3]]
    - ['9', [0, 2]]
    - ['a', [0, 1, 3]]
    - ['b', [0, 1, 2]]
    - ['c', [1, 2, 3]]
    - ['d', [0, 2, 3]]

# how far apart tiles are spaced (note that, in this case, this is less than the tile's dimensions)
tile_spacing: [2, 2]

# a list of list defining the maze structure - each element references a tile
maze:
    - ['4', 'c', '4', '7', 'a', '7', '4', '8', '7', '5', '7', 'a', '7', '4', '7', 'a', '3', '8', '8', '7']
    - ['9', '4', '6', '5', '8', '1', '6', '4', '1', 'c', '5', '7', '9', 'b', '0', '7', '5', '7', '4', '6']
    - ['9', '9', 'a', '8', '8', '7', '4', '6', '4', '8', '7', '9', '9', '4', '2', '9', '4', '6', '9', 'd']
    - ['9', '5', '7', 'a', '3', '6', '5', '8', '6', 'd', '5', '6', '5', '6', '9', '5', '6', 'd', '5', '2']
    - ['0', '7', '5', '7', '5', '8', '8', '7', '4', '2', '4', '8', '8', '8', '6', '4', '8', '2', 'd', '9']
    - ['9', '9', 'd', '5', '8', '8', '7', '5', '2', '9', '5', '3', '7', '4', '8', '6', '4', '2', '9', '9']
    - ['9', '9', '0', '8', '7', '4', '2', '4', '6', 'b', '4', '6', '5', '1', 'c', '4', '6', '9', '9', '9']
    - ['b', '9', '9', 'a', '6', '9', '9', '9', '4', '7', '5', '7', '4', '8', '7', '9', 'd', '9', '5', '6']
    - ['4', '6', '5', '8', '8', '6', '9', '5', '6', '0', '8', '6', '9', '4', '6', '9', '9', '9', '4', 'c']
    - ['9', '4', '7', '4', '8', '7', '9', '4', '8', '1', '7', '4', '6', '9', '4', '6', '5', '2', '5', '7']
    - ['9', '9', '0', '6', 'd', '5', '6', '5', '7', '4', '1', '6', 'd', '9', '9', 'd', '4', '6', 'a', '2']
    - ['9', 'b', '9', '4', '1', '7', 'a', '3', '6', '0', '3', '7', '5', '6', '9', '9', '5', 'c', '4', '6']
    - ['0', '8', '6', '5', 'c', '5', '8', '6', 'a', '6', '9', '5', '7', 'd', '5', '1', '7', '4', '1', '7']
    - ['0', '8', '8', '8', '8', '8', '8', '8', '7', 'a', '2', 'a', '6', '9', '4', '8', '2', '9', '4', '6']
    - ['5', '7', '4', '7', '4', '8', '8', 'c', '5', '7', '5', '8', '7', '9', '5', 'c', '5', '6', '5', '7']
    - ['d', '9', '9', '9', '9', '4', '8', '8', '8', '6', '4', 'c', '9', '9', '4', '3', '3', '7', 'a', '6']
    - ['5', '6', '9', '9', '5', '2', '4', '8', '3', '7', '9', '4', '1', '6', '9', '9', 'b', '5', '8', '7']
    - ['d', '4', '6', '0', '7', '9', '9', '4', '6', '9', '0', '6', '4', '8', '6', '9', '4', '8', '7', '9']
    - ['9', '5', '7', '9', '5', '2', '9', '5', '7', '5', '1', '8', '6', '4', 'c', '9', '9', 'a', '6', '9']
    - ['5', '8', '6', '5', 'c', '5', '6', 'a', '1', '8', '3', '8', 'c', '5', '8', '6', '5', '8', '8', '6']

# the namespace of the functions
namespace: 'maze/functions'
