# all configuration specific to generating ring

# radiuses used to generate the ring
radiuses:
    - 4
    - 8
    - 12
    - 16
    - 20
    - 24
    - 28
    - 32
    - 36
    - 40

# the namespace of the functions
namespace: 'ring'
