# all configuration specific to generating domes in the java version

# all blocks that the ring can be made of and their tag (to be used in the function name)
blocks_and_tags:
    - ['minecraft:lantern', 'lantern']
    - ['minecraft:sand', 'sand']

# the namespace of the functions
namespace: 'ring/functions'
