strip_namespace: true
block_name_map:
    "white_stained_glass_pane[]": "stained_glass_pane 0"
    "orange_stained_glass_pane[]": "stained_glass_pane 1"
    "magenta_stained_glass_pane[]": "stained_glass_pane 2"
    "light_blue_stained_glass_pane[]": "stained_glass_pane 3"
    "yellow_stained_glass_pane[]": "stained_glass_pane 4"
    "lime_stained_glass_pane[]": "stained_glass_pane 5"
    "pink_stained_glass_pane[]": "stained_glass_pane 6"
    "grey_stained_glass_pane[]": "stained_glass_pane 7"
    "light_grey_stained_glass_pane[]": "stained_glass_pane 8"
    "cyan_stained_glass_pane[]": "stained_glass_pane 9"
    "purple_stained_glass_pane[]": "stained_glass_pane 10"
    "blue_stained_glass_pane[]": "stained_glass_pane 11"
    "brown_stained_glass_pane[]": "stained_glass_pane 12"
    "green_stained_glass_pane[]": "stained_glass_pane 13"
    "red_stained_glass_pane[]": "stained_glass_pane 14"
    "black_stained_glass_pane[]": "stained_glass_pane 15"
    "structure_block[mode=load]": "structure_block 2"
    "pink_glazed_terracotta[facing=north]": "pink_glazed_terracotta"
    "pink_glazed_terracotta[facing=south]": "pink_glazed_terracotta"
    "pink_glazed_terracotta[facing=east]": "pink_glazed_terracotta"
    "pink_glazed_terracotta[facing=west]": "pink_glazed_terracotta"
    "chiseled_sandstone": "sandstone 1"
    "cut_sandstone": "sandstone 2"
    "smooth_sandstone": "sandstone 3"
    "sandstone_stairs[half=bottom,shape=straight,facing=east]": "sandstone_stairs 0"
    "sandstone_stairs[half=bottom,shape=straight,facing=west]": "sandstone_stairs 1"
    "sandstone_stairs[half=bottom,shape=straight,facing=south]": "sandstone_stairs 2"
    "sandstone_stairs[half=bottom,shape=straight,facing=north]": "sandstone_stairs 3"
    "quartz_stairs[half=bottom,shape=straight,facing=east]": "quartz_stairs 0"
    "quartz_stairs[half=bottom,shape=straight,facing=west]": "quartz_stairs 1"
    "quartz_stairs[half=bottom,shape=straight,facing=south]": "quartz_stairs 2"
    "quartz_stairs[half=bottom,shape=straight,facing=north]": "quartz_stairs 3"
    "scaffolding[distance=0]": "scaffolding"
    "sea_lantern": "sealantern"
    "water[level=0]": "water"
    "water[level=1]": null
    "water[level=2]": null
    "water[level=3]": null
    "water[level=4]": null
    "water[level=5]": null
    "water[level=6]": null
    "water[level=7]": null
    "water[level=8]": null
    "oak_fence": "fence 0"
    "spruce_fence": "fence 1"
    "birch_fence": "fence 2"
    "jungle_fence": "fence 3"
    "acacia_fence": "fence 4"
    "dark_oak_fence": "fence 5"
    "birch_fence[north=true]": "fence 2"
    "birch_fence[east=true]": "fence 2"
    "birch_fence[south=true]": "fence 2"
    "birch_fence[west=true]": "fence 2"
    "birch_fence[north=true,west=true]": "fence 2"
    "birch_fence[south=true,west=true]": "fence 2"
    "birch_fence[east=true,south=true]": "fence 2"
    "birch_fence[east=true,north=true]": "fence 2"
    "wall_torch[facing=north]": "torch 4"
    "wall_torch[facing=east]": "torch 1"
    "wall_torch[facing=south]": "torch 3"
    "wall_torch[facing=west]": "torch 2"
    "oak_slab[type=top]": "wooden_slab 8"
    "spruce_slab[type=top]": "wooden_slab 9"
    "birch_slab[type=top]": "wooden_slab 10"
