# https://minecraft-el.gamepedia.com/Data_values

strip_namespace: true

block_name_map:
    "white_terracotta": "stained_hardened_clay 0"
    "orange_terracotta": "stained_hardened_clay 1"
    "magenta_terracotta": "stained_hardened_clay 2"
    "light_blue_terracotta": "stained_hardened_clay 3"
    "yellow_terracotta": "stained_hardened_clay 4"
    "lime_terracotta": "stained_hardened_clay 5"
    "pink_terracotta": "stained_hardened_clay 6"
    "grey_terracotta": "stained_hardened_clay 7"
    "light_grey_terracotta": "stained_hardened_clay 8"
    "cyan_terracotta": "stained_hardened_clay 9"
    "purple_terracotta": "stained_hardened_clay 10"
    "blue_terracotta": "stained_hardened_clay 11"
    "brown_terracotta": "stained_hardened_clay 12"
    "green_terracotta": "stained_hardened_clay 13"
    "red_terracotta": "stained_hardened_clay 14"
    "black_terracotta": "stained_hardened_clay 15"
    "white_stained_glass_pane[]": "stained_glass_pane 0"
    "orange_stained_glass_pane[]": "stained_glass_pane 1"
    "magenta_stained_glass_pane[]": "stained_glass_pane 2"
    "light_blue_stained_glass_pane[]": "stained_glass_pane 3"
    "yellow_stained_glass_pane[]": "stained_glass_pane 4"
    "lime_stained_glass_pane[]": "stained_glass_pane 5"
    "pink_stained_glass_pane[]": "stained_glass_pane 6"
    "grey_stained_glass_pane[]": "stained_glass_pane 7"
    "light_grey_stained_glass_pane[]": "stained_glass_pane 8"
    "cyan_stained_glass_pane[]": "stained_glass_pane 9"
    "purple_stained_glass_pane[]": "stained_glass_pane 10"
    "blue_stained_glass_pane[]": "stained_glass_pane 11"
    "brown_stained_glass_pane[]": "stained_glass_pane 12"
    "green_stained_glass_pane[]": "stained_glass_pane 13"
    "red_stained_glass_pane[]": "stained_glass_pane 14"
    "black_stained_glass_pane[]": "stained_glass_pane 15"
    "white_stained_glass_pane[south=true,north=true]": "stained_glass_pane 0"
    "orange_stained_glass_pane[south=true,north=true]": "stained_glass_pane 1"
    "magenta_stained_glass_pane[south=true,north=true]": "stained_glass_pane 2"
    "light_blue_stained_glass_pane[south=true,north=true]": "stained_glass_pane 3"
    "yellow_stained_glass_pane[south=true,north=true]": "stained_glass_pane 4"
    "lime_stained_glass_pane[south=true,north=true]": "stained_glass_pane 5"
    "pink_stained_glass_pane[south=true,north=true]": "stained_glass_pane 6"
    "grey_stained_glass_pane[south=true,north=true]": "stained_glass_pane 7"
    "light_grey_stained_glass_pane[south=true,north=true]": "stained_glass_pane 8"
    "cyan_stained_glass_pane[south=true,north=true]": "stained_glass_pane 9"
    "purple_stained_glass_pane[south=true,north=true]": "stained_glass_pane 10"
    "blue_stained_glass_pane[south=true,north=true]": "stained_glass_pane 11"
    "brown_stained_glass_pane[south=true,north=true]": "stained_glass_pane 12"
    "green_stained_glass_pane[south=true,north=true]": "stained_glass_pane 13"
    "red_stained_glass_pane[south=true,north=true]": "stained_glass_pane 14"
    "black_stained_glass_pane[south=true,north=true]": "stained_glass_pane 15"
    "white_stained_glass_pane[east=true,west=true]": "stained_glass_pane 0"
    "orange_stained_glass_pane[east=true,west=true]": "stained_glass_pane 1"
    "magenta_stained_glass_pane[east=true,west=true]": "stained_glass_pane 2"
    "light_blue_stained_glass_pane[east=true,west=true]": "stained_glass_pane 3"
    "yellow_stained_glass_pane[east=true,west=true]": "stained_glass_pane 4"
    "lime_stained_glass_pane[east=true,west=true]": "stained_glass_pane 5"
    "pink_stained_glass_pane[east=true,west=true]": "stained_glass_pane 6"
    "grey_stained_glass_pane[east=true,west=true]": "stained_glass_pane 7"
    "light_grey_stained_glass_pane[east=true,west=true]": "stained_glass_pane 8"
    "cyan_stained_glass_pane[east=true,west=true]": "stained_glass_pane 9"
    "purple_stained_glass_pane[east=true,west=true]": "stained_glass_pane 10"
    "blue_stained_glass_pane[east=true,west=true]": "stained_glass_pane 11"
    "brown_stained_glass_pane[east=true,west=true]": "stained_glass_pane 12"
    "green_stained_glass_pane[east=true,west=true]": "stained_glass_pane 13"
    "red_stained_glass_pane[east=true,west=true]": "stained_glass_pane 14"
    "black_stained_glass_pane[east=true,west=true]": "stained_glass_pane 15"
    "glass_pane[south=true,north=true]": "glass_pane"
    "glass_pane[east=true,west=true]": "glass_pane"
    "structure_block[mode=load]": "structure_block 2"
    "pink_glazed_terracotta[facing=north]": "pink_glazed_terracotta"
    "pink_glazed_terracotta[facing=south]": "pink_glazed_terracotta"
    "pink_glazed_terracotta[facing=east]": "pink_glazed_terracotta"
    "pink_glazed_terracotta[facing=west]": "pink_glazed_terracotta"
    "chiseled_sandstone": "sandstone 1"
    "cut_sandstone": "sandstone 2"
    "smooth_sandstone": "sandstone 3"
    "sandstone_stairs[half=bottom,shape=straight,facing=east]": "sandstone_stairs 0"
    "sandstone_stairs[half=bottom,shape=straight,facing=west]": "sandstone_stairs 1"
    "sandstone_stairs[half=bottom,shape=straight,facing=south]": "sandstone_stairs 2"
    "sandstone_stairs[half=bottom,shape=straight,facing=north]": "sandstone_stairs 3"
    "quartz_stairs[half=bottom,shape=straight,facing=east]": "quartz_stairs 0"
    "quartz_stairs[half=bottom,shape=straight,facing=west]": "quartz_stairs 1"
    "quartz_stairs[half=bottom,shape=straight,facing=south]": "quartz_stairs 2"
    "quartz_stairs[half=bottom,shape=straight,facing=north]": "quartz_stairs 3"
    "scaffolding[distance=0]": "scaffolding"
    "sea_lantern": "sealantern"
    "water[level=0]": "water"
    "water[level=1]": null
    "water[level=2]": null
    "water[level=3]": null
    "water[level=4]": null
    "water[level=5]": null
    "water[level=6]": null
    "water[level=7]": null
    "water[level=8]": null
    "oak_fence": "fence 0"
    "spruce_fence": "fence 1"
    "birch_fence": "fence 2"
    "jungle_fence": "fence 3"
    "acacia_fence": "fence 4"
    "dark_oak_fence": "fence 5"
    "birch_fence[north=true]": "fence 2"
    "birch_fence[east=true]": "fence 2"
    "birch_fence[south=true]": "fence 2"
    "birch_fence[west=true]": "fence 2"
    "birch_fence[north=true,west=true]": "fence 2"
    "birch_fence[south=true,west=true]": "fence 2"
    "birch_fence[east=true,south=true]": "fence 2"
    "birch_fence[east=true,north=true]": "fence 2"
    "wall_torch[facing=north]": "torch 4"
    "wall_torch[facing=east]": "torch 1"
    "wall_torch[facing=south]": "torch 3"
    "wall_torch[facing=west]": "torch 2"
    "redstone_torch[]": "redstone_torch 5"
    "redstone_torch[facing=north]": "redstone_torch 4"
    "redstone_torch[facing=east]": "redstone_torch 1"
    "redstone_torch[facing=south]": "redstone_torch 3"
    "redstone_torch[facing=west]": "redstone_torch 2"
    "redstone_torch[lit=true]": "redstone_torch 5"
    "redstone_torch[lit=true,facing=north]": "redstone_torch 4"
    "redstone_torch[lit=true,facing=east]": "redstone_torch 1"
    "redstone_torch[lit=true,facing=south]": "redstone_torch 3"
    "redstone_torch[lit=true,facing=west]": "redstone_torch 2"
    "redstone_wall_torch[facing=north]": "redstone_torch 4"
    "redstone_wall_torch[facing=east]": "redstone_torch 1"
    "redstone_wall_torch[facing=south]": "redstone_torch 3"
    "redstone_wall_torch[facing=west]": "redstone_torch 2"
    "redstone_wall_torch[lit=true,facing=north]": "redstone_torch 4"
    "redstone_wall_torch[lit=true,facing=east]": "redstone_torch 1"
    "redstone_wall_torch[lit=true,facing=south]": "redstone_torch 3"
    "redstone_wall_torch[lit=true,facing=west]": "redstone_torch 2"
    "oak_slab[type=bottom]": "wooden_slab 0"
    "spruce_slab[type=bottom]": "wooden_slab 1"
    "birch_slab[type=bottom]": "wooden_slab 2"
    "jungle_slab[type=bottom]": "wooden_slab 3"
    "acacia_slab[type=bottom]": "wooden_slab 4"
    "dark_oak_slab[type=bottom]": "wooden_slab 5"
    "oak_slab[type=top]": "wooden_slab 8"
    "spruce_slab[type=top]": "wooden_slab 9"
    "birch_slab[type=top]": "wooden_slab 10"
    "jungle_slab[type=top]": "wooden_slab 11"
    "acacia_slab[type=top]": "wooden_slab 12"
    "dark_oak_slab[type=top]": "wooden_slab 13"
    "observer[facing=down]": "observer 0"
    "observer[facing=up]": "observer 1"
    "observer[facing=south]": "observer 2"
    "observer[facing=north]": "observer 3"
    "observer[facing=east]": "observer 4"
    "observer[facing=west]": "observer 5"
    "sticky_piston[facing=down]": "sticky_piston 0"
    "sticky_piston[facing=up]": "sticky_piston 1"
    "sticky_piston[facing=north]": "sticky_piston 2"
    "sticky_piston[facing=south]": "sticky_piston 3"
    "sticky_piston[facing=west]": "sticky_piston 4"
    "sticky_piston[facing=east]": "sticky_piston 5"
    "slime_block": "slime"
    "smooth_stone_slab[type=bottom]": "stone_slab 0"
    "cut_sandstone_slab[type=bottom]": "stone_slab 1"
    "smooth_stone_slab[type=top]": "stone_slab 8"
    "cut_sandstone_slab[type=top]": "stone_slab 9"
    "nether_brick_slab[type=top]" : "polished_blackstone_brick_slab 1" # TODO closest mapping I could find
    "nether_brick_slab[type=bottom]" : "polished_blackstone_brick_slab" # TODO closest mapping I could find
    "lantern[hanging=true]": "lantern 1"
    "ladder[facing=north]": "ladder 2"
    "ladder[facing=south]": "ladder 3"
    "ladder[facing=west]": "ladder 4"
    "ladder[facing=east]": "ladder 5"
    "bricks": "brick_block"
    "redstone_wire[east=side,south=side,north=side,west=side,power=15]": "redstone_wire"
    "redstone_wire[east=side,south=side,north=side,west=side,power=0]": "redstone_wire"
    "redstone_wire[east=side,south=none,north=none,west=side,power=15]": "redstone_wire"
    "rail[shape=north_south]": "rail 0" # Straight rail connecting to the north and south.
    "rail[shape=east_west]": "rail 1" # Straight rail connecting to the east and west.
    "rail[shape=ascending_east]": "rail 2" # Sloped rail ascending to the east.
    "rail[shape=ascending_west]": "rail 3" # Sloped rail ascending to the west.
    "rail[shape=ascending_north]": "rail 4" # Sloped rail ascending to the north.
    "rail[shape=ascending_south]": "rail 5" # Sloped rail ascending to the south.
    "rail[shape=south_east]": "rail 6" # Curved rail connecting to the south and east.
    "rail[shape=south_west]": "rail 7" # Curved rail connecting to the south and west.
    "rail[shape=north_west]": "rail 8" # Curved rail connecting to the north and west.
    "rail[shape=north_east]": "rail 9" # Curved rail connecting to the north and east.
    "powered_rail[shape=north_south]": "golden_rail 0" # Straight rail connecting to the north and south.
    "powered_rail[shape=east_west]": "golden_rail 1" # Straight rail connecting to the east and west.
    "powered_rail[shape=ascending_east]": "golden_rail 2" # Sloped rail ascending to the east.
    "powered_rail[shape=ascending_west]": "golden_rail 3" # Sloped rail ascending to the west.
    "powered_rail[shape=ascending_north]": "golden_rail 4" # Sloped rail ascending to the north.
    "powered_rail[shape=ascending_south]": "golden_rail 5" # Sloped rail ascending to the south.
    "repeater[delay=1,facing=north]": "repeater 0"
    "repeater[delay=1,facing=east]": "repeater 1"
    "repeater[delay=1,powered=true,facing=east]": "repeater 1" # TODO need to ignore powered=true
    "repeater[delay=1,facing=south]": "repeater 2"
    "repeater[delay=1,facing=west]": "repeater 3"
    "repeater[delay=2,facing=north]": "repeater 4"
    "repeater[delay=2,facing=east]": "repeater 5"
    "repeater[delay=2,facing=south]": "repeater 6"
    "repeater[delay=2,facing=west]": "repeater 7"
    "repeater[delay=3,facing=north]": "repeater 8"
    "repeater[delay=3,facing=east]": "repeater 9"
    "repeater[delay=3,facing=south]": "repeater 10"
    "repeater[delay=3,facing=west]": "repeater 11"
    "repeater[delay=4,facing=north]": "repeater 12"
    "repeater[delay=4,facing=east]": "repeater 13"
    "repeater[delay=4,facing=south]": "repeater 14"
    "repeater[delay=4,facing=west]": "repeater 15"
    "acacia_button[face=floor,facing=south]": "acacia_button 1"
    "acacia_button[face=floor,facing=north]": "acacia_button 1"

order_values:
    "lantern 1": 100
    "observer 0": 100
    "observer 1": 100
    "observer 2": 100
    "observer 3": 100
    "observer 4": 100
    "observer 5": 100
    "redstone_torch 1": 100
    "redstone_torch 2": 100
    "redstone_torch 3": 100
    "redstone_torch 4": 100
    "redstone_torch 5": 100
    "redstone_wire": 100
    "acacia_button 1": 100
    "golden_rail 0": 100
    "golden_rail 1": 100
    "golden_rail 2": 100
    "golden_rail 3": 100
    "golden_rail 4": 100
    "golden_rail 5": 100
    "rail 0": 100
    "rail 1": 100
    "rail 2": 100
    "rail 3": 100
    "rail 4": 100
    "rail 5": 100
    "rail 6": 100
    "rail 7": 100
    "rail 8": 100
    "rail 9": 100
    "repeater 1": 100
    "torch 1": 100
    "torch 2": 100
    "torch 3": 100
    "torch 4": 100
    "torch 5": 100

# The volume that the `structure bedrock` tool scans for structure blocks
volume_lower: [-100, 0, -100]
volume_upper: [100, 30, 100]

common_data_values:
    top_slot_bit: &top_slot_bit
        'top_slot_bit:0': 0
        'top_slot_bit:1': 8
    wood_type: &wood_type
        'wood_type:oak': 0
        'wood_type:spruce': 1
        'wood_type:birch': 2
        'wood_type:jungle': 3
        'wood_type:acacia': 4
        'wood_type:dark_oak': 5
    color: &color
        'color:white': 0
        'color:orange': 1
        'color:magenta': 2
        'color:light_blue': 3
        'color:yellow': 4
        'color:lime': 5
        'color:pink': 6
        'color:grey': 7
        'color:light_grey': 8 # TODO both?
        'color:silver': 8 # TODO both?
        'color:cyan': 9
        'color:purple': 10
        'color:blue': 11
        'color:brown': 12
        'color:green': 13
        'color:red': 14
        'color:black': 15
    direction: &direction
        'direction:0': 0
        'direction:1': 1
        'direction:2': 2
        'direction:3': 3
    stairs: &stairs
        'weirdo_direction:0': 0
        'weirdo_direction:1': 1
        'weirdo_direction:2': 2
        'weirdo_direction:3': 3
        'upside_down_bit:0': 0
        'upside_down_bit:1': 4
    facing_direction: &facing_direction
        'facing_direction:0': 0
        'facing_direction:1': 1
        'facing_direction:2': 2
        'facing_direction:3': 3
        'facing_direction:4': 4
        'facing_direction:5': 5
    block: &block
        'chisel_type:default': 0
        'chisel_type:chiseled': 1
        'chisel_type:lines': 2
        'chisel_type:smooth': 3
        'pillar_axis:x': 4 # TODO not sure
        'pillar_axis:y': 16 # TODO not sure
        'pillar_axis:z': 8 # TODO  not sure
    door: &door
        <<: *direction
        "door_hinge_bit:0": 0
        "door_hinge_bit:1": 4
        "open_bit:0": 0
        "open_bit:1": 0 #
        "upper_block_bit:0": 0
        "upper_block_bit:1": null #

data_value_map:
    ladder:
        <<: *facing_direction
    wall_sign:
        <<: *facing_direction
    stone_slab:
        'stone_slab_type:smooth_stone': 0
        'stone_slab_type:sandstone': 1
        'stone_slab_type:wood': 2
        'stone_slab_type:cobblestone': 3
        'stone_slab_type:brick': 4
        'stone_slab_type:stone_brick': 5
        'stone_slab_type:quartz': 6
        'stone_slab_type:nether_brick': 7
        <<: *top_slot_bit
    wooden_slab:
        <<: *wood_type
        <<: *top_slot_bit
    double_wooden_slab:
        <<: *wood_type
        <<: *top_slot_bit
    lantern:
        'hanging:0': 0
        'hanging:1': 1
    stained_hardened_clay:
        <<: *color
    concrete:
        <<: *color
    stained_glass_pane:
        <<: *color
    stained_glass:
        <<: *color
    redstone_wire:
        'redstone_signal:0': 0 # can be 0-15
    unpowered_repeater:
        <<: *direction
        'repeater_delay:0': 0
        'repeater_delay:1': 4
        'repeater_delay:2': 8
        'repeater_delay:3': 12
    piston:
        <<: *facing_direction
    water:
        'liquid_depth:0': 0
        'liquid_depth:1': 1
        'liquid_depth:2': 2
        'liquid_depth:3': 3
        'liquid_depth:4': 4
        'liquid_depth:5': 5
        'liquid_depth:6': 6
        'liquid_depth:7': 7
        'liquid_depth:8': 8
        'liquid_depth:9': 9
        'liquid_depth:10': 10
        'liquid_depth:11': 11
        'liquid_depth:12': 12
        'liquid_depth:13': 13
        'liquid_depth:14': 14
        'liquid_depth:15': 15
    fence:
        <<: *wood_type
    carpet:
        <<: *color
    planks:
        <<: *wood_type
    flower_pot:
        'update_bit:0': 0
        'update_bit:1': 1
    farmland:
        'moisturized_amount:0': 0
        'moisturized_amount:1': 1
        'moisturized_amount:2': 2
        'moisturized_amount:3': 3
        'moisturized_amount:4': 4
        'moisturized_amount:5': 5
        'moisturized_amount:6': 6
        'moisturized_amount:7': 7
    potatoes:
        'growth:0': 0
        'growth:1': 1
        'growth:2': 2
        'growth:3': 3
        'growth:4': 4
        'growth:5': 5
        'growth:6': 6
        'growth:7': 7
    bed:
        <<: *direction
        'head_piece_bit:0': null
        'head_piece_bit:1': 4
        'occupied_bit:0': 0
        'occupied_bit:1': 8
    stone:
        'stone_type:stone': 0
        'stone_type:granite': 1
        'stone_type:granite_smooth': 2
        'stone_type:diorite': 3
        'stone_type:diorite_smooth': 4
        'stone_type:andesite': 5
        'stone_type:andesite_smooth': 6
    dirt:
        'dirt_type:normal': 0
        'dirt_type:coarse': 1
    quartz_block:
        <<: *block
    purpur_block:
        <<: *block
    torch:
        'torch_facing_direction:west': 1
        'torch_facing_direction:east': 2
        'torch_facing_direction:north': 3
        'torch_facing_direction:south': 4
        'torch_facing_direction:up': 5
    red_nether_brick_stairs:
        <<: *stairs
    quartz_stairs:
        <<: *stairs
    stone_stairs:
        <<: *stairs
    smooth_quartz_stairs:
        <<: *stairs
    crimson_door:
        <<: *door
    dark_oak_door:
        <<: *door
    chain:
        'pillar_axis:x': 2
        'pillar_axis:y': 4
        'pillar_axis:z': 8
    furnace:
        <<: *facing_direction
    chest:
        <<: *facing_direction
    acacia_wall_sign:
        <<: *facing_direction
    warped_wall_sign:
        <<: *facing_direction
    soul_campfire:
        <<: *direction
        "extinguished:0": 0
        "extinguished:1": 4
    activator_rail:
        "rail_direction:0": 0
        "rail_direction:1": 1
        "rail_direction:2": 2
        "rail_direction:3": 3
        "rail_direction:4": 4
        "rail_direction:5": 5
        "rail_data_bit:0": 0
        "rail_data_bit:1": 8
    structure_block:
        "structure_block_type:save": null
    wooden_button:
        <<: *facing_direction
        "button_pressed_bit:0": 0
        "button_pressed_bit:1": 8
