# https://minecraft-el.gamepedia.com/Data_values

strip_namespace: true

common_data_values:
    top_slot_bit: &top_slot_bit
        'top_slot_bit:0': 0
        'top_slot_bit:1': 8
    wood_type: &wood_type
        'wood_type:oak': 0
        'wood_type:spruce': 1
        'wood_type:birch': 2
        'wood_type:jungle': 3
        'wood_type:acacia': 4
        'wood_type:dark_oak': 5
    color: &color
        'color:white': 0
        'color:orange': 1
        'color:magenta': 2
        'color:light_blue': 3
        'color:yellow': 4
        'color:lime': 5
        'color:pink': 6
        'color:grey': 7
        'color:light_grey': 8 # TODO both?
        'color:silver': 8 # TODO both?
        'color:cyan': 9
        'color:purple': 10
        'color:blue': 11
        'color:brown': 12
        'color:green': 13
        'color:red': 14
        'color:black': 15
    direction: &direction
        'direction:0': 0
        'direction:1': 1
        'direction:2': 2
        'direction:3': 3
    stairs: &stairs
        'weirdo_direction:0': 0
        'weirdo_direction:1': 1
        'weirdo_direction:2': 2
        'weirdo_direction:3': 3
        'upside_down_bit:0': 0
        'upside_down_bit:1': 4
    facing_direction: &facing_direction
        'facing_direction:0': 0
        'facing_direction:1': 1
        'facing_direction:2': 2
        'facing_direction:3': 3
        'facing_direction:4': 4
        'facing_direction:5': 5
    block: &block
        'chisel_type:default': 0
        'chisel_type:chiseled': 1
        'chisel_type:lines': 2
        'chisel_type:smooth': 3
        'pillar_axis:x': 4 # TODO not sure
        'pillar_axis:y': 16 # TODO not sure
        'pillar_axis:z': 8 # TODO  not sure
    door: &door
        <<: *direction
        "door_hinge_bit:0": 0
        "door_hinge_bit:1": 4
        "open_bit:0": 0
        "open_bit:1": 0 # always create closed door
        "upper_block_bit:0": 0
        "upper_block_bit:1": null # don't render this block of the door
    hanging: &hanging
        'hanging:0': 0
        'hanging:1': 1
    torch: &torch
        'torch_facing_direction:west': 1
        'torch_facing_direction:east': 2
        'torch_facing_direction:north': 3
        'torch_facing_direction:south': 4
    repeater: &repeater
        <<: *direction
        'repeater_delay:0': 0
        'repeater_delay:1': 4
        'repeater_delay:2': 8
        'repeater_delay:3': 12
    comparator: &comparator
        <<: *direction
        'output_subtract_bit:0': 0
        'output_subtract_bit:1': 4
        'output_lit_bit:0': 0
        'output_lit_bit:1': 8
    sandstone: &sandstone
        'sand_stone_type:chiseled': 1
        'sand_stone_type:cut': 2
        'sand_stone_type:smooth': 3

data_value_map:
    sandstone:
        <<: *sandstone
    red_sandstone:
        <<: *sandstone
    hopper:
        <<: *facing_direction
        "toggle_bit:0": 0
        "toggle_bit:8": 8
    dropper: # TODO extra nbt data
        <<: *facing_direction
        "triggered_bit:0": 0
        "triggered_bit:8": 8
    ladder:
        <<: *facing_direction
    wall_sign:
        <<: *facing_direction
    observer:
        <<: *facing_direction
        'powered_bit:0': 0
        'powered_bit:1': 8
    stone_slab:
        'stone_slab_type:smooth_stone': 0
        'stone_slab_type:sandstone': 1
        'stone_slab_type:wood': 2
        'stone_slab_type:cobblestone': 3
        'stone_slab_type:brick': 4
        'stone_slab_type:stone_brick': 5
        'stone_slab_type:quartz': 6
        'stone_slab_type:nether_brick': 7
        <<: *top_slot_bit
    wooden_slab:
        <<: *wood_type
        <<: *top_slot_bit
    double_wooden_slab:
        <<: *wood_type
        <<: *top_slot_bit
    lantern:
        <<: *hanging
    soul_lantern:
        <<: *hanging
    wool:
        <<: *color
    stained_hardened_clay:
        <<: *color
    concrete:
        <<: *color
    stained_glass_pane:
        <<: *color
    stained_glass:
        <<: *color
    redstone_wire:
        'redstone_signal:0': 0
        'redstone_signal:1': 1
        'redstone_signal:2': 2
        'redstone_signal:3': 3
        'redstone_signal:4': 4
        'redstone_signal:5': 5
        'redstone_signal:6': 6
        'redstone_signal:7': 7
        'redstone_signal:8': 8
        'redstone_signal:9': 9
        'redstone_signal:10': 10
        'redstone_signal:11': 11
        'redstone_signal:12': 12
        'redstone_signal:13': 13
        'redstone_signal:14': 14
        'redstone_signal:15': 15
    powered_repeater:
        <<: *repeater
    unpowered_repeater:
        <<: *repeater
    powered_comparator:
        <<: *comparator
    unpowered_comparator:
        <<: *comparator
    sticky_piston:
        <<: *facing_direction
    piston:
        <<: *facing_direction
    water:
        'liquid_depth:0': 0
        'liquid_depth:1': 1
        'liquid_depth:2': 2
        'liquid_depth:3': 3
        'liquid_depth:4': 4
        'liquid_depth:5': 5
        'liquid_depth:6': 6
        'liquid_depth:7': 7
        'liquid_depth:8': 8
        'liquid_depth:9': 9
        'liquid_depth:10': 10
        'liquid_depth:11': 11
        'liquid_depth:12': 12
        'liquid_depth:13': 13
        'liquid_depth:14': 14
        'liquid_depth:15': 15
    fence:
        <<: *wood_type
    carpet:
        <<: *color
    planks:
        <<: *wood_type
    flower_pot:
        'update_bit:0': 0
        'update_bit:1': 1
    farmland:
        'moisturized_amount:0': 0
        'moisturized_amount:1': 1
        'moisturized_amount:2': 2
        'moisturized_amount:3': 3
        'moisturized_amount:4': 4
        'moisturized_amount:5': 5
        'moisturized_amount:6': 6
        'moisturized_amount:7': 7
    potatoes:
        'growth:0': 0
        'growth:1': 1
        'growth:2': 2
        'growth:3': 3
        'growth:4': 4
        'growth:5': 5
        'growth:6': 6
        'growth:7': 7
    bed:
        <<: *direction
        'head_piece_bit:0': null
        'head_piece_bit:1': 4
        'occupied_bit:0': 0
        'occupied_bit:1': 8
    stone:
        'stone_type:stone': 0
        'stone_type:granite': 1
        'stone_type:granite_smooth': 2
        'stone_type:diorite': 3
        'stone_type:diorite_smooth': 4
        'stone_type:andesite': 5
        'stone_type:andesite_smooth': 6
    dirt:
        'dirt_type:normal': 0
        'dirt_type:coarse': 1
    quartz_block:
        <<: *block
    purpur_block:
        <<: *block
    torch:
        <<: *torch
        'torch_facing_direction:up': 5
    redstone_torch:
        <<: *torch
        'torch_facing_direction:top': 5
    unlit_redstone_torch:
        <<: *torch
        'torch_facing_direction:top': 5
    oak_stairs:
        <<: *stairs
    spruce_stairs:
        <<: *stairs
    birch_stairs:
        <<: *stairs
    jungle_stairs:
        <<: *stairs
    acacia_stairs:
        <<: *stairs
    dark_oak_stairs:
        <<: *stairs
    crimson_stairs:
        <<: *stairs
    warped_stairs:
        <<: *stairs
    normal_stone_stairs:
        <<: *stairs
    granite_stairs:
        <<: *stairs
    polished_granite_stairs:
        <<: *stairs
    diorite_stairs:
        <<: *stairs
    polished_diorite_stairs:
        <<: *stairs
    andesite_stairs:
        <<: *stairs
    polished_andesite_stairs:
        <<: *stairs
    stone_stairs:
        <<: *stairs
    mossy_cobblestone_stairs:
        <<: *stairs
    stone_brick_stairs:
        <<: *stairs
    mossy_stone_brick_stairs:
        <<: *stairs
    brick_stairs:
        <<: *stairs
    end_brick_stairs:
        <<: *stairs
    nether_brick_stairs:
        <<: *stairs
    red_nether_brick_stairs:
        <<: *stairs
    sandstone_stairs:
        <<: *stairs
    smooth_sandstone_stairs:
        <<: *stairs
    red_sandstone_stairs:
        <<: *stairs
    smooth_red_sandstone_stairs:
        <<: *stairs
    quartz_stairs:
        <<: *stairs
    smooth_quartz_stairs:
        <<: *stairs
    purpur_stairs:
        <<: *stairs
    prismarine_stairs:
        <<: *stairs
    prismarine_bricks_stairs:
        <<: *stairs
    dark_prismarine_stairs:
        <<: *stairs
    blackstone_stairs:
        <<: *stairs
    polished_blackstone_stairs:
        <<: *stairs
    polished_blackstone_brick_stairs:
        <<: *stairs
    crimson_door:
        <<: *door
    dark_oak_door:
        <<: *door
    chain:
        'pillar_axis:x': 2
        'pillar_axis:y': 4
        'pillar_axis:z': 8
    furnace:
        <<: *facing_direction
    chest:
        <<: *facing_direction
    acacia_wall_sign:
        <<: *facing_direction
    warped_wall_sign:
        <<: *facing_direction
    soul_campfire:
        <<: *direction
        "extinguished:0": 0
        "extinguished:1": 4
    activator_rail:
        "rail_direction:0": 0
        "rail_direction:1": 1
        "rail_direction:2": 2
        "rail_direction:3": 3
        "rail_direction:4": 4
        "rail_direction:5": 5
        "rail_data_bit:0": 0
        "rail_data_bit:1": 8
    structure_block:
        "structure_block_type:save": null
    structure_void:
        "structure_void_type:void": null
    wooden_button:
        <<: *facing_direction
        "button_pressed_bit:0": 0
        "button_pressed_bit:1": 8
    tnt:
        "allow_underwater_bit:0": 0
        "allow_underwater_bit:1": 1
        "explode_bit:0": 0
        "explode_bit:1": 2
    stonebrick:
        "stone_brick_type:cracked": 1
        "stone_brick_type:mossy": 2
        "stone_brick_type:chiseled": 3
        "stone_brick_type:smooth": 4

rotation_groups:
    - ['direction:0', 'direction:1', 'direction:2', 'direction:3']
    - ['weirdo_direction:0', 'weirdo_direction:2', 'weirdo_direction:1', 'weirdo_direction:3']
    - ['facing_direction:2', 'facing_direction:5', 'facing_direction:3', 'facing_direction:4']
    - ['torch_facing_direction:north', 'torch_facing_direction:east', 'torch_facing_direction:south', 'torch_facing_direction:west']
    - ["rail_direction:0", "rail_direction:1", "rail_direction:0", "rail_direction:1"]
    - ["rail_direction:2", "rail_direction:5", "rail_direction:4", "rail_direction:3"]

order_values:
    "lantern": 100
    "soul_lantern": 100
    "observer": 100
    "torch": 100
    "redstone_torch": 100
    "redstone_wire": 100
    "wooden_button": 100
    "activator_rail": 100
    "powered_repeater": 100
    "unpowered_repeater": 100
